### ISSUE TITLE
When will you upgrade the version of POI?

### ISSUE THREAD

**Issue by dargonwanglong** [joniles/mpxj#135]
In Apache POI up to 4.1.0, when using the tool XSSFExportToXml to convert user-provided Microsoft Excel documents, a specially crafted document can allow an attacker to read files from the local filesystem or from internal network resources via XML External Entity (XXE) Processing.

See detail: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-12415

**Comment by joniles** [comment]
Hi! I've avoided this version bump for a while as it means that the minimum version of Java will be 8 whereas presently you can get away with Java 1.6. In the past this has caused issues for a few users who don't have control over the Java version they work with (e.g. it comes with the application server platform they need to deploy to).

Anyhow, CVEs are probably the best reason to move forward. I'll post something to the mailing list to see what feedback we get, but I'll aim to make the switch in MPXJ 8.0.0. In the meantime I have fixed a trivial API incompatibility which means assuming you are already on Java 1.8 you can just drop in POI 4.1.1 as a replacement for the POI jar which ships with Procore (assuming you are using Java, it's a bit more involved if you're on .Net!). I've just merged the API fix, so that will form part of the next release.

**Comment by dargonwanglong** [comment]
Sounds good. We are already on Java 1.8, I will try this on next version. Thank you!

**Comment by joniles** [comment]
Hi! MPXJ 8.0.0 has been released, which includes Poi 4.1.1.
