### ISSUE TITLE
Not import PercentageComplete in P6 software

### ISSUE THREAD

**Issue by raviarsuda05** [joniles/mpxj#146]
I wrote on the MPX extension file by MPXWriter.  I set PercentageComplete. but When I will import xyz.mpx file in P6 software I can see task name and link hierarchy but I can't see PercentageComplete. Same issue with MSPDI.

**Comment by joniles** [comment]
Hi!

Does the schedule you created have resource assignments?
Can you attach a sample schedule here?

Thanks!

Jon

**Comment by raviarsuda05** [comment]
[100 Tasks XER (1).mpx.zip](https://github.com/joniles/mpxj/files/4203731/100.Tasks.XER.1.mpx.zip)

**Comment by raviarsuda05** [comment]
Hii,
Thank you. for your support. I attached zip file as per under

[Percentage Completion of Tasks.mpx.zip](https://github.com/joniles/mpxj/files/4203802/Percentage.Completion.of.Tasks.mpx.zip)

**Comment by joniles** [comment]
I had to hunt around a bit in the data to find a task with a percent complete value. The one I found was `Fourth D`. The values you have configured don't make sense (and MPXJ doesn't try to validate them):

* Duration: 40h
* Actual duration: 37h
* Remaining duration: 36h
* Percent complete: 10

I'd start by ensuring your data is consistent.

One thing that P6 may require in order to import successfully is Work to be defined as well as duration, so you could try supplying values for Work, Actual Work, Remaining Work.

If you are generating files to be consumed by other systems it can be a bit tricky to work out exactly which attributes they are using to generate the schedule. My suggestion would be to create a simple schedule in P6 showing percent complete for various activities and export that to see how P6 has configured the data. That'll give you an idea of how you'll need to set up the data in the file you are generating. You can also experiment by changing/removing data from the file P6 generates and reimporting to get an idea of what the minimum set of data needed is.

If you are specifically targeting P6 I would recommend generating a PMXML file from MPXJ - you might find it easier to communicate to P6 what you want if you are using its "native" format, and you can also compare that more readily with PMXML files exported by P6.

**Comment by raviarsuda05** [comment]
We have tried both PMXML file and MPX file. yet, both of them are showing faulty results for percentage. We also attempted to add an additional fields like Finish date, Actual duration and 
Duration. However, it is still showing funny results for percentages.

**Comment by joniles** [comment]
Hello, just reviewing open issues.

As I noted in my original response the values you're setting for each task don't seem to correlate. As per the example I highlighted in. my response above for the `Fourth D` task, if your duration (40h) and actual duration (37h) values are correct, then your remaining duration should be 3h and I would expect percent complete to be 92.5%. In your example the remaining duration is set to 36h and percent complete is 10%.

I'm going to close the ticket for now - I'll be pleased to reopen if you've reviewed the attributes you are exporting and are happy that they are consistent (as per my example above) then I'm happy to take another look.
