### ISSUE TITLE
ASTA Milestone Constraints are not processed

### ISSUE THREAD

**Issue by d6mck** [joniles/mpxj#161]
Powerproject milestones can have constraints, but they are not brought over by mpxj.

I have patched AstaReader.java to achieve this, by creating a milestone-specific, slightly tweaked copy of processConstraints(), which is then called from populateMilestones().

There is potentially a refinement to the new routine to differentiate between AS_LATE_AS_POSSIBLE and START_NO_EARLIER_THAN under certain circumstances, possibly involving predecessors (or lack thereof), which we are currently investigating.

[AstaReader.patch.txt](https://github.com/joniles/mpxj/files/4952202/AstaReader.patch.txt)

**Comment by joniles** [comment]
Hi, thanks for the patch. I have your code up and running. I'm wondering if the existing `processConstraints` code is actually wrong... if it is then we can potentially correct it and use just one method rather than having `processConstraints` and `processMilestoneConstraints`.

Here's the relevant code:

```java
// processConstraints
case 0:
{
   if (row.getInt("PLACEMENT") == 0)
   {
      constraintType = ConstraintType.AS_SOON_AS_POSSIBLE;
   }
   else
   {
      constraintType = ConstraintType.AS_LATE_AS_POSSIBLE;
   }
   break;
}
```


```java
// processMilestoneConstraints
case 0:
{
   if (row.getInt("PLACEMENT") == 1)
   {
      // If has no predecessor, then should this be START_NO_EARLIER_THAN? How would we check this?
      constraintType = ConstraintType.AS_LATE_AS_POSSIBLE;
   }
   else
   {
      constraintType = ConstraintType.AS_SOON_AS_POSSIBLE;
   }
   break;
}
```

As it stands currently, `processConstraints` will generate the following constraint types based on the Placement setting:

Placement Value | Placement Name | MPXJ Constraint Type
-|-|-
0 | ASAP | AS_SOON_AS_POSSIBLE
1 | ALAP | AS_LATE_AS_POSSIBLE
2 | ASAP Force Critical | AS_LATE_AS_POSSIBLE

Whereas, `processMilestoneConstraints` will generate these:

Placement Value | Placement Name | MPXJ Constraint Type
-|-|-
0 | ASAP | AS_SOON_AS_POSSIBLE
1 | ALAP | AS_LATE_AS_POSSIBLE
2 | ASAP Force Critical | AS_SOON_AS_POSSIBLE


The result from `processConstraints` generates `AS_LATE_AS_POSSIBLE` from `ASAP Force Critical` which seems ... counter intuitive. I think both methods should actually be generating the same output - what do you think?

**Comment by d6mck** [comment]
I think that's all correct, and the two can be combined.

We've been looking further into the AS_LATE_AS_POSSIBLE vs. START_NO_EARLIER_THAN issue, and it would appear that both milestones and tasks with no predecessors will be exported from Powerproject with START_NO_EARLIER_THAN rather than AS_LATE_AS_POSSIBLE.

Been trying to get my head around how to do this. The processPredecessors() method could post-process, but it would have to avoid changing genuine START_NO_EARLIER_THANs.

Attached are some example PP files and their XML output from Powerproject. The files have either milestones or tasks. The two groups are (1) linked with a lag; (2) lag removed; (3) link removed.

Leaving for the weekend now but I'll be back Monday.

[mpxj asta tests.zip](https://github.com/joniles/mpxj/files/4966858/mpxj.asta.tests.zip)

**Comment by d6mck** [comment]
I've implemented a solution to the AS_LATE_AS_POSSIBLE vs. START_NO_EARLIER_THAN issue. I added a new constraint type which is assigned to the indeterminate milestones and tasks. The processPredecessors() method then overwrites these as appropriate when establishing links, and finally post-processes the entire list of tasks and milestones to tidy up any remaining indeterminate values.

I also combined `processConstraints()` and `processMilestoneConstraints()`.

Two patch files attached.

[AstaReader.patch.txt](https://github.com/joniles/mpxj/files/4989059/AstaReader.patch.txt)
[ConstraintType.patch.txt](https://github.com/joniles/mpxj/files/4989060/ConstraintType.patch.txt)

**Comment by joniles** [comment]
I've just merged a change based on your patches. I took a slightly different approach with regard to deferring the decision on the `START_NO_EARLIER_THAN` versus `AS_LATE_AS_POSSIBLE` constraint types. Rather than creating a new constraint type I've just  collected the set of task unique IDs which need to be revisited and used that to drive the decision logic. Let me know if the updated code doesn't work as you expect!
