### ISSUE TITLE
How to realize what is the type of  the file in runtime

### ISSUE THREAD

**Issue by gregra81** [joniles/mpxj#162]
As part of our process, we're getting the file to be extracted in runtime, without the file extension. Is there a way to understand which file type is it (XER, XML, MPP, etc)?

**Comment by joniles** [comment]
If you need to understand the file type in order to pick the correct MPXJ reader, you can avoid that and just use the `UniversalProjectReader`. It will work out the file type for you from the content and choose the appropriate reader.

If you want to know _after_ you opened the file what kind of file it was there are two methods which categorize the type of schedule:

```java
ProjectProperties props = projectFile.getProjectProperties();
String application = props.setFileApplication();
String type = props.setFileType();
```

**Comment by gregra81** [comment]
@joniles Thank you very much!
