### ISSUE TITLE
Use in C#

### ISSUE THREAD

**Issue by erw13n** [joniles/mpxj#216]
I try to follow the tutorial on https://www.mpxj.org/howto-start.html
But the method for project.getAllResources, project.getAllTasks, project.getChildTasks is not available
So I'm wonder how to read the MPP file in C#

**Comment by ndarlington** [comment]
For the most part, the wrapper for C# provides some properties you can access for these sort of things instead of methods.  Java doesn't have properties, so the core API still depends on getter/setter methods with explicit names.

So generally speaking, when you set project.getTasks, try just project.Tasks instead and you can foreach() over it.

```cs
foreach(Task task in project.Tasks) {
// do things with task
}
```

I run into some exceptions with this where I still revert to java style usage, but a lot of the time you won't have to.

**Comment by joniles** [comment]
I'm going to close this as I think @ndarlington's description sums up the situation nicely. I am planning to put together some better language-specific documentation in future which should hopefully make it easier to get started with MPXJ.
