### ISSUE TITLE
9.3.0 PMXML baselines return null

### ISSUE THREAD

**Issue by wildeyes** [joniles/mpxj#221]
Using `.getBaselineStart` or `.getBaselineFinish` returns null for my PMXML file. 
For a similiar MPP file baselines return fine.

The file has both a project and baselineProject exported.

Looking at the decompiled code:

```
    private void populateBaselines(List<ProjectFile> projects) {
        Map<Integer, ProjectFile> map = (Map)projects.stream().collect(Collectors.toMap((p) -> {
            return p.getProjectProperties().getUniqueID();
        }, (p) -> {
            return p;
        }));
        Iterator var3 = projects.iterator();

        while(var3.hasNext()) {
            ProjectFile project = (ProjectFile)var3.next();
            ProjectFile baseline = (ProjectFile)map.get(project.getProjectProperties().getBaselineProjectUniqueID());
            if (baseline != null) {
                project.setBaseline(baseline, (t) -> {
                    return t.getCanonicalActivityID();
                });
            }
        }
    }
```

I'm seeing that the attachment of baseline project is done via a "baselineProjectUniqueID", but my baselineProjectId is set to null, `<CurrentBaselineProjectObjectId xsi:nil="true" />`. 

What I'm failing to understand, is why attach the baselineProject via an id, if a there can only be one baselineProject in PMXML?

Attached are zipped 3 files, xls, pdf and xml of the files from P6:
[PMXML baselines return null.zip](https://github.com/joniles/mpxj/files/6460099/PMXML.baselines.return.null.zip)

**Comment by joniles** [comment]
Hi, thanks for the report.

MPXJ is set up to use the `CurrentBaselineProjectObjectId` attribute in the exported PMXML file to identify the baseline to import. This corresponds to the "Project Baseline" setting in P6. In your sample file this attribute is not populated, which suggests that the "Project Baseline" in P6 is set to "Current Schedule".  In this case the baseline values should be taken from the Planned attributes (Planned Start, Planned Finish, etc). This functionality has only relatively recently been added to MPXJ so you'll need to be working with version 9.2.0 or later to see these values populated. I've imported your sample file locally to confirm that the baseline attributes are being populated. If you're not seeing this you may want to validate which version of MPXJ is being included in your project.

PMXML files can contain multiple baseline projects, and combined with the expected behavior when `CurrentBaselineProjectObjectId` is not set (treating the planned attributes as the baseline) then we can't make any assumptions about how we should use baseline projects which appear in the PMXML file.

You can however manually manage the baseline yourself by using the `readAll` method of the reader class to read all of the projects contained in the file, then explicitly apply a baseline to your schedule. The code would look like this in Java:

```java
project.setBaseline(baselineProject, t -> t.getCanonicalActivityID());
```
(The lambda in the second argument generates the key used to match tasks between the main project and its baseline).

Hope that helps!
