### ISSUE TITLE
Start date fetching error

### ISSUE THREAD

**Issue by zxgjava** [joniles/mpxj#231]
![image](https://user-images.githubusercontent.com/11919245/122372399-374f0600-cf93-11eb-8ad5-a35b37195b11.png)
![image](https://user-images.githubusercontent.com/11919245/122372619-65cce100-cf93-11eb-9f4e-64c6bcc9b0a1.png)
The start date in the MPP file is empty, call ‘getStart()’ to return a specific date

**Comment by joniles** [comment]
Hi! Thanks for the note. The date itself is valid (it'll be what MS Project uses to show roughly the bounds of a manually scheduled task before a user supplies explicit dates). I appreciate that you need to have access to a flag to indicate if this date is actually shown in MS Project. I'd need to undertake some investigation work in order to determine how MS Project is representing this. I'll add this to my "to do" list, but I'm afraid that it's not something I can prioritise at present. I will update this issue when I do have a chance to take a look.
