### ISSUE TITLE
MPP fields Methods Not Available 

### ISSUE THREAD

**Issue by amitparsha** [joniles/mpxj#339]
Hey, 

I am using the methods as  provided in [docs](https://www.mpxj.org/apidocs/net/sf/mpxj/Task.html) 
to get the task column value corresponding to MPP field.

There are many MPP fields whose methods are not available.
I am listing the column types for  some of them as  follows:

Group By Summary
Ignore Warnings
Placeholder
Publish
Response Pending
Warning
Status Manager
Health
Task Summary Name
Sprint
Status
Status Indicator
Deliverable Finish
Deliverable Start
Baseline Deliverable Start
Baseline Deliverable Finish
Baseline 1-10 Deliverable Finish (Baseline1 Deliverable Finish, ..., Baseline10 Deliverable Finish)
Baseline 1-10 Deliverable Start (Baseline1 Deliverable Start, ..., Baseline10 Deliverable Start)
Sprint Start
Sprint Finish
Deliverable Type
Scheduled Duration
Negative Slack
Baseline Budget Work
Baseline1-10 Budget Cost(Baseline1 Budget Cost, ..., Baseline10 Budget Cost)
Baseline1-10 Cost (Baseline1 Cost, ..., Baseline10 Cost)
Budget Cost
Cost Rate Table
Cost1-10(Cost1, ..., Cost10)
Enterprise Cost1-10 (Enterprise Cost1, ..., Enterprise Cost10)
CV%
SV%
SPI
CPI
TCPI

there are some more...

Do we have any support to get the value for these column types/MPP fields ?

**Comment by joniles** [comment]
In general, if there is not an accessor/modifier method for a particular field, you can gain access to it via the `getCurrentValue()` and `set()` methods on the task. For example: 

```
task.getCurrentValue(TaskField.IGNORE_WARNINGS);
```

Here are some notes on the fields you mention above.

**Group By Summary**: this is a field which is generated by the MS Project UI when you select a "group by" setting for tasks. This column indicates the difference between actual task rows and rows generated to show the grouping. There is no data for MPXJ to read.

**Ignore Warnings**: we're not currently reading this value from MPP files, I will look at this in future.

**Placeholder**: this appears to be a generated value, the value will be true if the task is manually scheduled and the start/finish/duration are not all present. I may add support for this in future.

**Publish**: we're not currently reading this value from MPP files, I will look at this in future.

**Response Pending**: I've added getter and setter methods for this.

**Warning**: not sure if this value is present in MPP files, would need to see some sample data to see if this can be implemented or if this is value dynamically generated at runtime by MS Project.

**Status Manager**:  would need to see some sample data with tasks that have different status managers assigned. It looks like Project Server is only storing a UUID/Unique ID for this attribute in the MPP file, and we may not be able to look up the user details without a connection to project server.

**Health**: this is one of the default enterprise custom fields configured on Project Server. I'd recommend exploring the data returned by `ProjectFile.getCustomFields()` to access this value.

**Task Summary Name**: generated dynamically by MS Project: returns the parent summary task name. I'll consider implementing support for this in future.

**Sprint Fields**: will need to do more work to retrieve the sprint details from an MPP file. For now the best you can get is the Sprint ID.

**Status**: Dynamically generated by MS Project. I will consider implementing support for this in future.

**Status Indicator**: dynamically generated graphical indicator, equivalent to the status attribute. This will not be supported by MPXJ.

**Deliverable Fields**: in my instance of Project Server I don't see a way to create/assign deliverables to a task. I'm happy to look at the fields relating to deliverables if I can be provided with some sample data.

**Scheduled Duration**: I've added getter and setter methods for this

**Negative Slack**:  I can't find this field in MS Project

**Budget Attributes**: I've added methods for the various budget cost, work and baseline fields.

**Cost Rate Table**: this is an assignment attribute, it appears as a task attribute so that it can be used as a column heading in tables, but only assignments will have a value.

**Cost1-10**: see the `Task.getCost(int index)` method

**Enterprise Cost1-10**: see the `Task.getEnterpriseCost(int index)` method.

**CV%, SV%, SPI, CPI, TCPI**: as far as I can tell all of these values are dynamically generated by MS Project.I will lok into implementing the relevant calculation for these attributes in future.

**Comment by joniles** [comment]
PR with changes noted in the comments above. https://github.com/joniles/mpxj/pull/352

**Comment by joniles** [comment]
The changes noted above have now ben merged.
