### ISSUE TITLE
.Net Core 3.1 - PowerProject - "1 is not a supported code page"

### ISSUE THREAD

**Issue by mstfgueclue** [joniles/mpxj#358]
## General Information
I am trying to parse a PowerProject document and I get the following error message from UniversalProjectReader `System.ArgumentException: '1 is not a supported code page.'`

I even have the same error message when I try to parse a PowerProject file with the .Net sample project that you provided
  - The link to the sample project I used is [this](https://github.com/joniles/mpxj/tree/master/src.net/samples/MpxjConvert)
 
## Used Tech
- .Net Core 3.1 
- installed `net.sf.mpxj-for-csharp V10.10.0 `, which was released yesterday (2022-09-13)
  - I have tested all versions up to `V10.5.0` and had the same behavior

**Comment by joniles** [comment]
Hello! Could you provide a sample Powerproject file which exhibits this behavior, and also if possible a stack trace for the exception. Thanks!

**Comment by mstfgueclue** [comment]
> Hello! Could you provide a sample Powerproject file which exhibits this behavior, and also if possible a stack trace for the exception. Thanks!

Thanks for the quick reply. Yes, for sure! In the attachment you will find the stack trace and a PowerProject sample document.
[dotnet-powerproject-error.zip](https://github.com/joniles/mpxj/files/9564650/dotnet-powerproject-error.zip)

**Comment by joniles** [comment]
Ah! I think it's this issue:

https://www.mpxj.org/faq/#net-core

Hopefully adding 

```c#
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
```

to your code will fix the problem.

**Comment by mstfgueclue** [comment]
> Ah! I think it's this issue:
> 
> https://www.mpxj.org/faq/#net-core
> 
> Hopefully adding
> 
> ```cs
> System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
> ```
> 
> to your code will fix the problem.

Unfortunately, it didn't help :/ 

And yes, I have also tried the following steps:  
  - solution and project cleanup
  - cleared NuGet cache
  - reinstalled the MPXJ packages from NuGet
  - used different encodings

But based on the answer in the FAQ on the MPXJ website, the project you provided should work because it runs on .NET Framework 4.8. I do get the same error in that project, though.

Here again the part of the FAQ answer I refer to :
> By default .NET Core does not include all of the character encodings which may be used by MPXJ (__and which are present by default in .NET Framework__).

**Comment by joniles** [comment]
OK, leave it with me, let me try and reproduce the issue here...

**Comment by joniles** [comment]
Unfortunately I wasn't able to reproduce the issue locally.

I did search around for the error message `1 is not a supported code page` and it seems to crop up for various libraries and software products, which suggests this is more of a Windows issue rather than MPXJ:

https://github.com/icsharpcode/SharpZipLib/issues/195
https://knowledge.autodesk.com/support/vault-products/troubleshooting/caas/sfdcarticles/sfdcarticles/Error-ADMS-Console-1-is-not-a-supported-code-page-Parameter-name-codepage.html
https://stackoverflow.com/questions/66910777/1-is-not-a-supported-code-page-jetbrains-rider

One of the suggested solutions which seems to come up regularly is:

```
Set the first Preferred Language to "English (United States)" under the Language section in the Settings App
(Start Menu -> Settings -> Time & Language -> Language).
```

Hopefully this will work for you, but you may still also need to include the `System.Text.Encoding.RegisterProvider(...)` code I mentioned before.
