### ISSUE TITLE
Reading tasks from a subproject when it's part of a master file

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#400]
Hi,

In MSP you can create a so called Master file that you can import sub projects into. When the master file is exported to xml format it seems like all the tasks of the subprojects are included. Can these be read using mpxj? When I debug through the import it doesn't seem like it but maybe there is a setting somewhere that I've missed. 

I've attached an example of a master file containing two sub projects with two activities in each. It looks like this in MSP:
![image](https://user-images.githubusercontent.com/9571179/203547906-746ec7de-42da-49c9-9b8d-4ca074a68d66.png)
The activities A, A2, B1 and B21 exist in the file but I can't figure out how to read them using mpxj.

[Master.zip](https://github.com/joniles/mpxj/files/10075479/Master.zip)

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment]
Interesting! I hadn't seen the XML used by MS Project to embed a project like this. I'll have a think about the best way to handle this.

**Comment by fdahlberg** [comment]
Sounds great Jon! Have a think and let us know. We would really like this functionality.

**Comment by joniles** [comment]
Interesting... you only get the nested `<project>` tags if the sub project is expanded in the MPP file when the XML file is exported. If the sub project is not expanded when the xml is exported, all you'll get is the normal `<SubprojectName>c:\path\to\child1.mpp</SubprojectName>` entry.

Microsoft Project itself won't read the nested `<project>` tags, it insists on trying to find the original subproject MPP files.

**Comment by joniles** [comment]
@fdahlberg quick update from me: in MPXJ 11.4.0 I've undertaken some refactoring to improve the way external projects and external task predecessors are handled by MPXJ, which is the foundational work I needed to do in order to read this embedded project data from MSPDI files. I'll be taking a look at that shortly. In the meantime you may find the documentation [here](https://www.mpxj.org/howto-use-external-projects/) useful win regard to working with external projects when reading MPP files.
