### ISSUE TITLE
Error: Negative Values Timephased When There's Decimal

### ISSUE THREAD

**Issue by evertondevelop** [joniles/mpxj#465]
Hey, dude! I found something weird. I'll send you a .MPP file that has 3 tasks and they're all have negative value when export to XML.

![Screenshot 2023-03-22 112215](https://user-images.githubusercontent.com/62966401/226935919-0d1c8d03-6810-411d-8990-813da6fbe46d.png)

And beyond that, some values is wrong on the XML, like a day 3/9.
![Screenshot 2023-03-22 112319](https://user-images.githubusercontent.com/62966401/226936470-e7c19e7b-6b5d-4c22-8553-725461cd8749.png)

I hope your help.
Thanks!

**Comment by diegosechin-timenow** [comment]
Hi @joniles.
Tks for your support.

have you saw it? It's causing us a lot of problems, because it's blocking the use of the importation, because this kind of error stop the process.

One example is: "There is an error in XML document (276027, 15).
System.Private.Xml
at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) at TimeConnect.Schedulers.ReaderXmlFile.HandlerReadXml.Read(Byte[] fileXml) at TimeConnect.Schedulers.ScheduleProcess.Reading.Function.ReadingFunc.Run(String processJson, FunctionContext context) in D
\Dev\TimeNow\timeconnect-process-steps\TimeConnect.Schedulers.ScheduleProcess.Reading.Function\ReadingFunc.cs
line 103"

**Comment by joniles** [comment]
@diegosechin-timenow Thanks for the note. The problem you've noted above:

> There is an error in XML document (276027, 15) ...

is this the same thing that @evertondevelop opened this issue for, if not could you open a separate issue? Thanks!

**Comment by diegosechin-timenow** [comment]
It's the same problem, but another example. It is ocorring in many schedules.

**Comment by joniles** [comment]
Is this a file which you have created using MPXJ?

Can you attach a sample file which causes the failure you indicated?

Thanks

**Comment by diegosechin-timenow** [comment]
Follow.
![image](https://user-images.githubusercontent.com/93920995/228544179-51305c8c-aa6b-4ec6-a879-ee56042d953b.png)
[17ff7a2a-c0ed-4795-9f9f-67dc739980b7 (1).zip](https://github.com/joniles/mpxj/files/11101149/17ff7a2a-c0ed-4795-9f9f-67dc739980b7.1.zip)

@joniles

**Comment by joniles** [comment]
I've merged a fix for this, it'll be in the next MPXJ release.

**Comment by diegosechin-timenow** [comment]
Thanks, you have idea when this version will be released?
