### ISSUE TITLE
Issue with Asta PP files when we build solution on docker (Linux)

### ISSUE THREAD

**Issue by ndinesh231** [joniles/mpxj#537]
Hi @joniles , Can you please confirm on this ?
https://github.com/joniles/mpxj/issues/536

Thanks,
Dinesh

**Comment by ndinesh231** [comment]
Hi @joniles 

We are trying to use this lib on Linux docker container, and its failing for 
Asta PP files with below error.
**Unable to load shared library 'ikvm-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libikvm-native: No such file or directory.**

Issue : https://github.com/joniles/mpxj/issues/536

We made all the config to copy native libs to target folder but still we are getting same error.
'libikvm-native.so' is loaded but looks like it is depending on another library which is not there in the target folder.

Can we know how to solve this? do we have any document for linux setup?
What are the dependencies we are using within .so file ?
Are we using proper .so file for Linux architecture? 


Thanks, 
Dinesh

**Comment by joniles** [comment]
Hello! Just to confirm, I have used MPXJ on Linux, and also deployed it with Linux using Docker, so it is possible!

First question: what is your target architecture? There is not currently an Arm version of the native libraries used by MPXJ, so that would be an issue.

Assuming you are targeting an Intel architecture, could you create a simple "hello world" style docker config which hosts a few lines of code in the language you are working in to invoke one of the MPXJ reader classes and open a sample PP file. If you can reproduce the problem using this setup I can take a look.

I'm assuming you enabled the `LD_DEBUG` env var - if so, what new output did you get?

If you can post full console logs of the failure here that may also be helpful.

**Comment by joniles** [comment]
@ndinesh231 as this issue has been inactive for a while now, I'm going to close it. Feel free to post further information here or reopen it if this is still an issue and you have new information available.
