### ISSUE TITLE
Extraction Issues with MPXJ 11.5.4 and above

### ISSUE THREAD

**Issue by VipulADSK** [joniles/mpxj#545]
Hi @joniles 

We have tried upgrading our Stack to use MPXJ Version 11.5.4 from 11.2.0 and we found two issues with them which were working fine on 11.2.0.

1. I am not getting the Critical path of one of the Schedule files.[VM Demo 1 - December.xer.zip](https://github.com/joniles/mpxj/files/12211579/VM.Demo.1.-.December.xer.zip) for any of the activities which used to work earlier in 11.2.0.

2. Few of MPP files are failing to extract. [MSProjectCustomerFileBenold.mpp.zip](https://github.com/joniles/mpxj/files/12211592/MSProjectCustomerFileBenold.mpp.zip), [SampleBuilding_CustomFields.mpp.zip](https://github.com/joniles/mpxj/files/12211593/SampleBuilding_CustomFields.mpp.zip). These files have Custom Fields which we are trying to extract and it is working fine when using 11.2.0 but when upgrading to 11.5.4 we see that the extraction fails with exactly the same code which used to work on 11.2.0. 

The above two problem remains even in latest 12.x version. Can you please help us here.

**Comment by joniles** [comment]
Hi @VipulADSK, quick update on the XER file. A change was made to MPXJ between the versions of MPXJ you mention as the code was previously treating some `null` durations read from the file as a zero duration rather than a "not present" duration. In turn this meant that the critical flag was being set incorrectly for some activities.

I imported your sample file into P6 and on the face of it looks like MPXJ is correct, the "as imported" file shows no critical tasks in P6. I think this is simply a reflection of the fact that the project had not be scheduled in P6 before it was originally exported. If I run schedule on the data in P6 then export the file again, and finally re-read it using MPXJ, I'm seeing the critical flag set appropriately on the sample of activities I checked.

**Comment by joniles** [comment]
I forgot to mention yesterday, but there is potentially an issue (unrelated to your sample XER file) with rolling up the Critical flag to WBS/Summary tasks which I will take a look at when I'm back at my desk.

I will also get you some feedback on the sample MPP files as soon as I can.

**Comment by VipulADSK** [comment]
@joniles - Thanks for the updates.

I tried the XER and it seems you are right. But I am confused because it is impossible to get the data date without it been scheduled. These schedules were scheduled earlier using an older P6 version. Maybe something changed between the Software in between in P6 causing this. I will take a look at it better.

I will be waiting for your response with MPP files.

**Comment by joniles** [comment]
Hi @VipulADSK, I had some time today to take a quick look at the sample MPP files you provided. In both cases I was able to open the supplied files using the latest MPXJ code, without error. I also exported both files to JSON using the latest MPXJ code (I use JsonWriter to dump most of the data contained in a schedule file in a format which allows for "diff" comparisons), and exported to JSON using the older 11.2.0 code. I wasn't able to see any difference in the custom fields for these files between the two MPXJ versions. Can you highlight any particular data you are able to retrieve with 11.2.0 and can no longer see with 12.x code? Thanks!

**Comment by VipulADSK** [comment]
@joniles Thanks your your detailed reply. We checked in from our side and seems like we had some unhandled scenarios in our code which caused this error while parsing the file. We have fixed this and see they Import just fine. So I would close this ticket now.

Thank you for all your help. :)

**Comment by VipulADSK** [comment]
Closing the ticket as resolved.
