### ISSUE TITLE
Converted XER and XML can't be loaded in Asta/P6

### ISSUE THREAD

**Issue by maratos92** [joniles/mpxj#591]
Hi, 

I just started using the tool and I wanted to create some sort of a converter since the software licenses are expensive. 
I use Asta and P6 but some of my colleagues use only one software, so it's uncomfortable to ask people every time you need to convert a programme. I wrote a short script using your library to convert MPP, PP, XER and XML to XER and XML formats. It worked fine but when I tried to import the converted files in P6 or Asta it looked like the files weren't converted correctly. I also used a default converter (from P6, MP and Asta) and most of the times converted files from the software were imported into another software without problems. I also opened converted XERs (one by mpxj and another converted by Planning software) since I know the structure more or less and it looks like the XER writer misses a lot of fields when converting, even project name, currencies and many other fields. Is there a chance that I'm not using the library functions correctly? There's only one conversion that really worked fine - MPP to XML import to Asta. XER files weren't recognized by any software. 
I'm attaching a report, the files that I tried to convert and the script that I wrote. 
[Converter_rev03_test.xlsx](https://github.com/joniles/mpxj/files/12895548/Converter_rev03_test.xlsx)
[Samples.zip](https://github.com/joniles/mpxj/files/12895559/Samples.zip)
[Schedule_Converter_rev03_desktop.zip](https://github.com/joniles/mpxj/files/12895565/Schedule_Converter_rev03_desktop.zip)

**Comment by joniles** [comment]
Hi @maratos92 thanks for the samples and your notes on testing.

In many cases the issue was simply a mismatch between the attributes populated by one schedule application, and what another schedule application is expecting to be populated when it reads a file. I've made a number of changes to MPXJ to try and improve the situation. The results of these changes are summarised in the table below. The input files used in these tests were the sample files you provided.

From | To | P6 | Asta | Notes
-- | -- | -- | -- | --
MPP | XER | Y | N |  
MPP | PMXML | Y | Y |  
MPP | MSPDI | Y | Y |  
PP | XER | Y | N | P6: confirmed relationships loaded ok
PP | PMXML | Y | N | P6: Needs to be scheduled, Asta: save operation failed
PP | MSPDI | Y | N | Asta doesn't recognise this as a valid MSPDI file, imports into MS Project OK
XER | XER | Y | Y |  
XER | PMXML | Y | Y |  
XER | MSPDI | Y | N | Asta has problems with the data, but doesn't give useful diagnostics in the log file, imports OK into MS Project
MSPDI | XER | Y | N |  
MSPDI | PMXML | Y | Y |  
MSPDI | MSPDI | Y | N | Asta says the file is invalid, imports OK into MS Project

In general P6 seems to be happy to import any XER, PMXML or MSPDI files MPXJ writes.

Unfortunately the import functionality in Powerproject is much more conservative about what it will accept. It's very hit-and-miss about whether it will read a given MSPDI or PMXML file (although PMXML files are mostly successful) and the diagnostic information Powerproject produces is not sufficient for me to fix what it is complaining about.

I was able to get Powerproject to import an XER file re-written by MPXJ from an XER file. In this case all of the data Powerproject is expecting is present in the file. For other examples, if the activity records are deleted, Powerproject would import the rest of the XER fil. I believe that it is just missing activity record data which is causing Powerproject to have problems. In particular I think it is missing early/late start/finish dates, which are not always present in other schedule files, and which MPXJ doesn't presently calculate.

I'm just testing the changes I've made to MPXJ and will merge them later today. These changes will be available in the next release.

**Comment by maratos92** [comment]
Thanks for your prompt response @joniles ! 
Looking forward to trying the updated version. One more question regarding P6, do you use the standalone or the EPPM version? Since I have the P6 EPPM there might be some variables/fields (such as Currency, Projects settings, coding like UTF-8, UOM, financial periods etc.) not allowing the import and they were set up and blocked by administrator. Is there a chance that it could be the reason for import failure?

**Comment by joniles** [comment]
@maratos92 I only have access to the standalone version of testing. It's certainly possible that an EPPM admin setting might prevent certain data being imported, although I'm not sure if that would affect the success of an import as a whole or whether the forbidden data would just be ignored.

**Comment by maratos92** [comment]
Hi, @joniles just wondering if I can use the library with the changes that you made or do I need to wait for another release?

**Comment by joniles** [comment]
Hello! I thought I was going to have time to add more things before making a release, but didn't quite manage it. Anyhow, I've just made a new release which has the relevant changes.
