### ISSUE TITLE
Duplication of tasks when P6 exported xml iwth baseline

### ISSUE THREAD

**Issue by giladgreen** [joniles/mpxj#706]
Hey,

when user create a schedule with baseline in P6, and then export it to xml, the result file (attached) tasks are treated as seperate tasks and the result is duplication (see output file example)

![compare](https://github.com/joniles/mpxj/assets/10262587/b22d2dce-d9db-4ecb-b095-8bbc56df0011)

(the input file is XML, i had to rename it to txt to attach it here)

[With_Baseline.txt](https://github.com/user-attachments/files/15818200/With_Baseline.txt)

[output.json](https://github.com/user-attachments/files/15818209/output.json)

**Comment by joniles** [comment]
Hi Gilad, thanks for opening the issue and providing the sample file. I opened the sample file using MPXJ 12.10.2 and I'm able to read three distinct schedules from the file, each with their own separate WBS and Activities. Looking at the JSON file you've provided, I'm assuming you are undertaking some post-processing on the data from MPXJ to generate the JSON format you are working with. Is it possible that during this processing the data from the three schedules is being merged accidentally?

Jon

**Comment by giladgreen** [comment]
Hey Jon

" and I'm able to read three distinct schedules from the file" - that is the issue.. its not 3 different schedules..  the original P6 file is one project, with a baseline..  we expect the result to have this activities only once, and only one result project

**Comment by MadaraUchiha** [comment]
Hi Jon, I'm @giladgreen 's colleague.

The way we process multi-project schedules is that we merge them, such that they appear as the same logical schedule on the other end (the user is responsible for picking which schedules the extract, so that they are shown as one in the UI)

The bug is that the baselines are read by MPXJ as their own projects, we've been calling `universal.readAll()` from the beginning of time and this is a relatively new (as far as we can tell) issue, and specifically with PMXML.

**Comment by joniles** [comment]
Interesting! Let's see if we can get to the bottom of this...

So the behaviour of `readAll` to return both the main project and baseline projects from PMXML has been in place since February 2021 (https://github.com/joniles/mpxj/commit/a9070923005d1a95ac557d7402a03a207136a9b4), so that bit isn't recent. The other relevant recent change I can think of was a big refactor to the internals of `UniversalProjectReader` to introduce `ProjectReaderProxy` which happened in April this year and went into version 12.9.0.

To see if this did have an effect, I just checked out 12.8.0 and used the "project explorer" UI which ships with MPXJ to open the file, and selected the "Open All" option which uses `UniversalProject.readAll` and I still get three distinct projects being retrieved. Just to be sure I went back to 12.0.0 and repeated the same test with the same results.

Can you confirm which MPXJ version you are working with currently? If you look at your version control history, can you roll back the MPXJ versions to see at what point you get back to the behaviour you are expecting?

**Comment by giladgreen** [comment]
Jon,

can we use the:
projectFile.getProjectProperties().getBaselineTypeName()

and be sure that only the <BaselineProject> would return a non-NULL value there?

**Comment by joniles** [comment]
`getBaselineTypeName` depends on the content of the PMXML file, so it could easily not be present.

It would probably be best for me to add a separate flag set by MPXJ to ensure you can distinguish between baseline and non-baseline projects. Would that work for you?

**Comment by giladgreen** [comment]
yes, that would help a lot..

is the baseline feature relevant only to PMXML?

**Comment by joniles** [comment]
> is the baseline feature relevant only to PMXML?

Yes, at the moment as that's the only file format which could return a mixture of projects and baselines. Powerproject may end up being able to do this: at the moment although MPXJ is reading embedded baseline schedules from PP files, it doesn't make them available to the caller.

**Comment by joniles** [comment]
Hello! I'm going to close this issue now on the assumption you have what you need - feel free to update the issue or create a new one if you still have problems.
